### ISSUE TITLE
Revamp About Page 

### ISSUE THREAD

**Issue by BarakStout** [raft-tech/raft-tech.github.io#97]
- [x] Add a team grid layout to about page (@meissadia) 
- [x] Create profile pages (@BarakStout) 
- [x] Update profile bios

**Comment by BarakStout** [comment]
The data for the about page and the individual profile pages will be stored in a `.yml` file. Jekyll has built in the capability to access the data within our templet files. You can read up on [Jekyll Datafile](https://jekyllrb.com/docs/datafiles/) the tl;dt, we are going to have a file similar to this one:

```yml
# about.yml
- full_name: "Professor X"
  permalink: "professor_x"
  webpage: "http://en.wikipedia.org/wiki/Professor_X"
  github: profx
  role: faculty
  bio: |
    Professor X is the leader and founder of X-Men.
- full_name: "Scott Summers"
  permalink: "scott_summers"
  webpage: "http://en.wikipedia.org/wiki/Cyclops_(comics)"
  role: staff
  bio: |
    Scott, also known as Cyclops, shoots lasers from his eyes, which makes him the perfect administrative assistant.
```

In `_layout` files, we can do things like this:

```html
<ul>
{% for person in site.data.about %}
  <li>
    {{ person.full_name }}
  </li>
{% endfor %}
</ul>
```

This can help build the about page and solve that portion.

For each person to have a unique url/page, we will need to do a couple of extra steps locally. Since we use GitHub Pages to generate the website, we can't run custom plugins on the site that do things during build time. However, we can generate `.md` files locally and push them to the repo. This will create a sub-folder with a `.md` file for each person. We will only need to do this for edits to people's profiles or adding new members.
